services:
  orderservice.api:
    image: orderserviceapi
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB_HOST=mongodb-container
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=OrdersDatabase
      - UsersMicroserviceName=apigateway
      - UsersMicroservicePort=8080
      - ProductMicroserviceName=apigateway
      - ProductMicroservicePort=8080
      - DOTNET_RUNNING_IN_CONTAINER=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=guest
      - RabbitMQ_Password=guest
      - RabbitMQ_Port= 5672 
      - RabbitMQ_Products_Exchange=product.exchange
    ports:
      - "7000:8080"
    networks:
      - orders-mongodb-network
      - ecommerce-network
    depends_on:
      - mongodb-container


  mongodb-container:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ../mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - orders-mongodb-network


  product-microservice:
    image: product-microservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - MYSQL_HOST=mysql-container
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ecommerceproductsdatabase 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=guest
      - RabbitMQ_Password=guest
      - RabbitMQ_Port= 5672 
      - RabbitMQ_Products_Exchange=product.exchange
    ports:
      - "6001:8080"
    networks:
      - products-mysql-network
      - ecommerce-network
    depends_on:
      - mysql-container
  

  mysql-container:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"
    volumes:
      - ../mysql-init:/docker-entrypoint-initdb.d
    networks:
      - products-mysql-network

  users-microservice:
    image: user-microservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8181
      - POSTGRES_HOST=postgres-container
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - RabbitMQ_HostName=rabbitmq
      - RabbitMQ_UserName=guest
      - RabbitMQ_Password=guest
      - RabbitMQ_Port= 5672 
    ports:
      - "5000:8181"
    networks:
      - users-postgres-network
      - ecommerce-network
    depends_on:
      - postgres-container

  postgres-container:
    image: postgres:18.0
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eCommerceUsers
    ports:
      - "5433:5432"
    volumes:
      - ../postgres-init:/docker-entrypoint-initdb.d
    networks:
      - users-postgres-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - D:\Learn\ecommerce\redis-cache:/data
    networks:
      - ecommerce-network


  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
      - "7777:8080"
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports: 
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASSWORD=guest
    networks:
     - ecommerce-network

networks:
  orders-mongodb-network:
    driver: bridge
  products-mysql-network:
    driver: bridge
  users-postgres-network:
    driver: bridge
  ecommerce-network:
    driver: bridge
